call add_drug_translation ("abacavir (ABC) 300mg","Abacavir (ABC)");
call add_drug_translation ("acetazolamide 250mg","Acetazolamida");
call add_drug_translation ("acetylsalicylic acid 100mg","Acido acetilsalicílico");
call add_drug_translation ("aciclovir 200mg","Aciclovir");
call add_drug_translation ("albendazole 200mg","Albendazol");
call add_drug_translation ("albuterol 0.5ml solution of 5% (2.5mg)","Albuterol");
call add_drug_translation ("allopurinol 100mg","Alopurinol");
call add_drug_translation ("aluminium hydroxide 500mg","Hidroxido de aluminio");
call add_drug_translation ("amiloride 5mg","Amilorida");
call add_drug_translation ("aminophylline 100mg","Aminofilina");
call add_drug_translation ("amitriptyline HCl 25mg tablet","Amitriptilina");
call add_drug_translation ("amodiaquine HCl, equivalent to 200mg","Amodiaquina");
call add_drug_translation ("amoxicillin 125mg/5ml, 100ml","Amoxicilina");
call add_drug_translation ("amoxicillin 500mg + clavulanic acid 125mg","Amoxicilina 500 mg + Acido clavulánico 125 mg");
call add_drug_translation ("amphotericin b, 50mg (10ml)","Anfotericina B");
call add_drug_translation ("ampicillin 1 gram","Ampicilina ");
call add_drug_translation ("antacida (aluminium+magnesiumhydroxide) 300ml","Hidroxido de aluminio + Hidroxido de magnesio 400 mg + 400 mg/5mL");
call add_drug_translation ("anti-haemorrhoid 30g","Antihemorroide");
call add_drug_translation ("anti-rabies immunoglobuline, human 300iu/2ml","Inmunoglobulina antirrabica humana");
call add_drug_translation ("anti-snake bite serum, Africa (10 snakes), 10ml","Suero antiofídico polivalente");
call add_drug_translation ("artemether 20mg + lumefantrine 120mg (Coartem)","Artemeter 20 mg + Lumefantrina 120 mg");
call add_drug_translation ("artesunate 100mg","Artesunato");
call add_drug_translation ("asunaprevir, 100mg","Asunaprevir");
call add_drug_translation ("atazanavir (ATV) 150mg","Atazanavir (ATV)");
call add_drug_translation ("atenolol 100mg","Atenolol");
call add_drug_translation ("atropine sulphate 1%, 5ml","Atropina sulfato");
call add_drug_translation ("azathioprine 50mg","Azatioprina");
call add_drug_translation ("azithromycine 200mg/5ml, 15ml","Azitromicina");
call add_drug_translation ("beclometasone oral inhaler, 50mcg/dose, 200 doses","Beclometasona");
call add_drug_translation ("benzathine penicillin 1.2 miu","Penicilina benzatinica");
call add_drug_translation ("benzylbenzoate 25% application, 1 liter","Benzoato de bencilo");
call add_drug_translation ("benzylpenicillin 1 miu","Bencil penicilina");
call add_drug_translation ("betamethasone 0.1%, 15g","Betametasona");
call add_drug_translation ("biperiden HCl 2mg","Biperideno");
call add_drug_translation ("bisacodyl 5mg","Bisacodilo");
call add_drug_translation ("bleomycin, 15.000 IU","Bleomicina");
call add_drug_translation ("bupivacaine 0.5%, 20ml","Bupivacaina");
call add_drug_translation ("","Bromuro de Ipatropio 20 mcg/dosis");
call add_drug_translation ("calcium gluconate 1g/10ml (2.23mmol)","Gluconato de calcio");
call add_drug_translation ("captopril 25mg","Captopril");
call add_drug_translation ("carbamazepine 200mg","Carbamazepina");
call add_drug_translation ("cefalexin 500mg","Cefalexina");
call add_drug_translation ("cefixime 200 mg","Cefixima");
call add_drug_translation ("ceftriaxone 1g","Ceftriaxona");
call add_drug_translation ("chloramphenicol 0.5%, eye drops, 10ml","Cloranfenicol");
call add_drug_translation ("chloroquine phosphate 100mg","Cloroquina fosfato");
call add_drug_translation ("chlorphenamine maleate 10mg/ml, 1ml","Clorfenamina maleato");
call add_drug_translation ("chlorpromazine HCl 100mg","Clorpromazina");
call add_drug_translation ("ciprofloxacin 250mg","Ciprofloxacino");
call add_drug_translation ("clotrimazole 1%, 20g tubes","Clotrimazol");
call add_drug_translation ("co-trimoxazole 100mg+20mg","Cotrimoxazol");
call add_drug_translation ("codeine phosphate 30mg","Codeina fosfato");
call add_drug_translation ("dapsone 100mg","Dapsona");
call add_drug_translation ("dexamethasone 0.5mg","Dexametasona");
call add_drug_translation ("dextrose 10% in water, 500ml bag","Dextrosa 10%");
call add_drug_translation ("dextrose 2.5% in NaCl 0.45%, 1000ml bag","Dextrosa 2.5%");
call add_drug_translation ("dextrose 5% in water, 1000ml bag","Dextrosa 5%");
call add_drug_translation ("dextrose 50%, 50ml","Dextrosa 50%");
call add_drug_translation ("diazepam 10mg/2ml","Diazepam");
call add_drug_translation ("diclofenac sodium 25mg","Diclofenaco sodico");
call add_drug_translation ("didanosine (DDI) 125mg","Didanosina (DDI)");
call add_drug_translation ("digoxine 0.25mg","Digoxina");
call add_drug_translation ("dimenhydrinate 50 mg","Dimenhidrinato");
call add_drug_translation ("dolutegravir (DTG) 10mg","Dolutegravir (DTG)");
call add_drug_translation ("dopamine HCl 200mg/5ml","Dopamina");
call add_drug_translation ("doxycycline 100mg","Doxiciclina");
call add_drug_translation ("efavirenz (EFV) 200mg","Efavirenz (EFV)");
call add_drug_translation ("emtricitabine (FTC) 10mg/ml oral solution, 170ml","Emtricitabina");
call add_drug_translation ("entecavir   0.05 mg/ mL","Entecavir");
call add_drug_translation ("ephedrine HCl 30mg/ml, 1ml","Efedrina");
call add_drug_translation ("epinephrine 1mg/ml, 1ml (adrenaline)","Epinefrina");
call add_drug_translation ("ergometrine maleate 0.5mg/ml, 1ml","Ergometrina maleato");
call add_drug_translation ("ergotamine 1mg + caffeine 100 mg","Ergotamina");
call add_drug_translation ("erythromycin 125mg/5ml, oral powder, 100ml","Eritromicina");
call add_drug_translation ("ethinylestradiol/levonorgestrel 0.03/0.15mg, 28","Levonorgestrel 0.15 mg + etinilestradiol 0.03 mg");
call add_drug_translation ("etravirine (ETR) 100mg","Etravirina (ETR)");
call add_drug_translation ("fentanyl 0.1mg/2ml","Fentanilo");
call add_drug_translation ("ferrous fumarate 100mg/5ml oral suspension, 5 liter","Fumarato ferroso");
call add_drug_translation ("ferrous sulphate 200mg + folic acid 0.25mg","Sulfato ferroso");
call add_drug_translation ("fluconazole 150mg","Fluconazol");
call add_drug_translation ("fluoxetine 20mg","Fluoxetina");
call add_drug_translation ("folic acid 5mg","Acido fólico");
call add_drug_translation ("furosemide 20mg/2ml","Furosemida");
call add_drug_translation ("gentamicin 0.3% eye drops, 5ml","Gentamicina");
call add_drug_translation ("glibenclamide 5mg","Glibenclamida");
call add_drug_translation ("griseofulvin 125mg","Griseofulvina");
call add_drug_translation ("haloperidol 5mg","Haloperidol");
call add_drug_translation ("heparine sodium 5000 iu/ml, 5ml","Heparina sódica");
call add_drug_translation ("hydrochlorothiazide 25mg","Hidroclorotiazida");
call add_drug_translation ("hydrocortisone 100mg (as sodium succinate)","Hidrocortisona");
call add_drug_translation ("hyoscine butylbromide 10mg","Hioscina butilbromuro");
call add_drug_translation ("ibuprofen 200mg","Ibuprofeno");
call add_drug_translation ("indometacin 25mg","Indometacina");
call add_drug_translation ("interferon pegylated alpha 2A, 135µg/0.5ml","Interferon alfa 2A");
call add_drug_translation ("interferon pegylated alpha 2B, 120 µg, powder+ solvent 0.5ml","Interferon alfa 2B");
call add_drug_translation ("isosorbide dinitrate 5mg","Isosorbide dinitrato");
call add_drug_translation ("ketamine 50mg/ml, 10ml","Ketamina");
call add_drug_translation ("ketoconazole 200mg","Ketoconazol");
call add_drug_translation ("lamivudine (3TC) 10mg/ml oral solution, 240ml","Lamivudina (3TC)");
call add_drug_translation ("levodopa/carbidopa 100mg/25mg","Carbidopa 25mg + Levodopa 250mg");
call add_drug_translation ("levonorgestrel 0.75mg","Levonorgestrel 0.75 mg");
call add_drug_translation ("levothyroxine sodium 0.1mg","Levotiroxina sódica");
call add_drug_translation ("lidocaine HCl 1%, 20ml","Lidocaína");
call add_drug_translation ("loperamide HCl 2mg","Loperamida");
call add_drug_translation ("lopinavir/ritonavir (LPV/ RTV) 200mg/50mg","Lopinavir 200mg + Ritonavir 50 mg (LPV/RTV)");
call add_drug_translation ("lorazepam 0.5mg","Lorazepam");
call add_drug_translation ("magnesium sulphate 50%, 20ml","Sulfato de magnesio");
call add_drug_translation ("mannitol 20% solution, 500ml","Manitol");
call add_drug_translation ("mebendazole 100mg","Mebendazol");
call add_drug_translation ("medroxyprogesteronacetate 150mg/ml, 1ml","Medroxiprogesterona acetato");
call add_drug_translation ("metformine HCl 500mg","Metformina");
call add_drug_translation ("methotrexate 2.5mg","Metotrexato");
call add_drug_translation ("methyldopa 250mg","Metildopa");
call add_drug_translation ("metoclopramide HCl 10mg","Metoclopramida");
call add_drug_translation ("metronidazole 125mg/5ml","Metronidazol");
call add_drug_translation ("miconazole 2% cream, 30g","Miconazol");
call add_drug_translation ("morphine sulfate 10mg/ml, 1ml","Morfina sulfato");
call add_drug_translation ("multivitamin","Multivitamínico");
call add_drug_translation ("nalidixic acid 500mg","Acido nalidíxico");
call add_drug_translation ("naloxone 0.4mg/ml, 1ml","Naloxona");
call add_drug_translation ("neomycin 0.5% + bacitracin 500 iu/g","Neomicina + Bacitracina");
call add_drug_translation ("nevirapine (NVP) 100mg","Nevirapina (NVP)");
call add_drug_translation ("nifedipine 20mg","Nifedipino");
call add_drug_translation ("nitroglycerine 0.5mg (glyceryl trinitrate)","Nitroglicerina");
call add_drug_translation ("nystatin 100.000 iu","Nistatina");
call add_drug_translation ("omeprazole 20mg","Omeprazol");
call add_drug_translation ("ondansetron 4mg","Ondansetron");
call add_drug_translation ("Oral Rehydration Salts 20.5g/liter (low osmolarity) for 1 litre","Sales de rehidratación oral");
call add_drug_translation ("oxytocin 10 iu/ml, 1ml","Oxitocina");
call add_drug_translation ("paracetamol 100mg","Paracetamol");
call add_drug_translation ("phenobarbital 100mg","Fenobarbital");
call add_drug_translation ("phenytoin 100mg","Fenitoina");
call add_drug_translation ("pilocarpine HCl 2% eye drops, 5ml","Pilocarpina clorhidrato");
call add_drug_translation ("potassium chloride 1 g/10ml","Potasio cloruro");
call add_drug_translation ("praziquantel 600mg","Prazicuantel");
call add_drug_translation ("prednisolone 5mg","Prednisolona");
call add_drug_translation ("procaine penicillin 1 miu","Penicilina procaínica");
call add_drug_translation ("progesterone 25mg/ml, 1ml in oil","Progesterona");
call add_drug_translation ("propranolol HCl 40mg","Propanolol");
call add_drug_translation ("protamine sulphate 50mg/5ml","Protamina sulfato");
call add_drug_translation ("pyrantel 250mg","Pirantel");
call add_drug_translation ("raltegravir (RAL) 100mg","Raltegravir (RAL)");
call add_drug_translation ("ranitidine 150mg","Ranitidina");
call add_drug_translation ("ribavirin 100 mg/ml","Ribavirina");
call add_drug_translation ("Ringer's lactate (Hartmann's solution) 1000ml","Lactato de Ringer");
call add_drug_translation ("risperidone 0.5mg","Risperidona");
call add_drug_translation ("ritonavir (RTV) 100mg","Ritonavir (RTV)");
call add_drug_translation ("salbutamol 0.1 mg/dose (200 doses/inhaler)","Salbutamol 100 mcg/dosis");
call add_drug_translation ("salbutamol 0.5mg/ml","Salbutamol");
call add_drug_translation ("sertraline 25mg","Sertralina");
call add_drug_translation ("silver sulfadiazine 1%","Sulfadiazina de plata");
call add_drug_translation ("sodium bicarbonate 8.4%","Bicarbonato de sodio");
call add_drug_translation ("sodium chloride 0.9%, 1000ml","Cloruro de sodio 0.9%");
call add_drug_translation ("spironolactone 25mg","Espironolactona");
call add_drug_translation ("stavudine (d4T) 15mg","Estavudina");
call add_drug_translation ("tenofovir (TDF) 150mg","Tenofovir (TDF)");
call add_drug_translation ("tetracycline HCl 1% eye ointment, 5g","Tetraciclina");
call add_drug_translation ("thiopental sodium 1g","Tiopental sódico");
call add_drug_translation ("timolol 0.5 % eye drops, 5ml","Timolol 0.5%");
call add_drug_translation ("tinidazole 500mg","Tinidazol");
call add_drug_translation ("tramadol HCl 100mg/2ml","Tramadol ");
call add_drug_translation ("valproic acid 150mg","Acido valproico");
call add_drug_translation ("verapamil HCl 40mg","Verapamilo");
call add_drug_translation ("vitamin A 50.000 iu (retinol)","Vitamina A (retinol)");
call add_drug_translation ("vitamin B1 100mg/2ml (thiamine HCl)","Vitamina B1 (tiamina)");
call add_drug_translation ("vitamin B12 1mg/ml (cyanocobalamine)","Vitamina B12 (cianocobalamina)");
call add_drug_translation ("vitamin B6 100mg/2ml (pyridoxine HCl)","Vitamina B6 (piridoxina)");
call add_drug_translation ("vitamin C 250mg (ascorbic acid)","Vitamina C (ácido ascórbico)");
call add_drug_translation ("vitamin K1 1mg/ml (phytomenadione)","Vitamina K1 (fitomedianona)");
call add_drug_translation ("warfarin sodium 5mg","Warfarina");
call add_drug_translation ("zidovudine (AZT) 100mg","Zidovudina (AZT)");
call add_drug_translation ("zidovudine/lamivudine/nevirapine (AZT/3TC/NVP) 60 mg/30 mg/50 mg","Zidovudina/Lamivudina/Nevirapina (AZT/3TC/NVP) 300/150/200 mg");
call add_drug_translation ("zinc dispersable tablet 20mg (as zinc sulphate)","Zinc");
