call add_concept_translation (35,"Documento");
call add_concept_translation (47,"Es anormal");
call add_concept_translation (83,"Estómago vacío");
call add_concept_translation (86,"En la noche");
call add_concept_translation (89,"Como se indica");
call add_concept_translation (153,"En prisión");
call add_concept_translation (160,"Si");
call add_concept_translation (161,"No");
call add_concept_translation (165,"No programado");
call add_concept_translation (195,"Cigarrillo al día");
call add_concept_translation (196,"Drogas intravenosas durante el año pasado");
call add_concept_translation (197,"Programa TB MDR");
call add_concept_translation (198,"Flujo de trabajo TB MDR");
call add_concept_translation (201,"Prueba de sensibilidad revisada (médico de TB primario)");
call add_concept_translation (202,"TB curado");
call add_concept_translation (205,"TB fracaso");
call add_concept_translation (207,"Paciente transferido");
call add_concept_translation (209,"Resultado del Programa TB MDR");
call add_concept_translation (210,"Decisión de iniciar un tratamiento de segunda línea (Comité de Tuberculosis)");
call add_concept_translation (211,"Régimen eficaz prescrito (neumólogo)");
call add_concept_translation (213,"Régimen recibido en el centro de salud");
call add_concept_translation (214,"Terapia directamente observada y paciente monitorizado por complicaciones");
call add_concept_translation (257,"Después del fracaso del primer tratamiento con drogas de primera línea");
call add_concept_translation (258,"Después del fracaso del régimen de retratamiento con drogas de primera línea");
call add_concept_translation (348,"Perdido en el seguimiento");
call add_concept_translation (374,"Tétanos neonatal");
call add_concept_translation (378,"Paperas");
call add_concept_translation (381,"Filariasis");
call add_concept_translation (382,"Malaria clínica");
call add_concept_translation (385,"Fiebre del dengue");
call add_concept_translation (386,"Diagnóstico general");
call add_concept_translation (390,"Bacteriología");
call add_concept_translation (395,"Proporciones");
call add_concept_translation (405,"Estado del programa EndTB");
call add_concept_translation (415,"No necesita tratamiento");
call add_concept_translation (418,"Flujo de trabajo del programa de tratamiento corto");
call add_concept_translation (426,"Régimen de 20 meses");
call add_concept_translation (427,"Flujo de trabajo del programa de régimen de 20 meses");
call add_concept_translation (429,"Programa de TB drogosensible");
call add_concept_translation (431,"Flujo de trabajo del Programa de TB drogosensible");
call add_concept_translation (432,"Resultado del Programa de TB drogosensible");
call add_concept_translation (474,"No resuelto");
call add_concept_translation (475,"Resuelto");
call add_concept_translation (476,"Resuelto con secuela");
call add_concept_translation (477,"Resolviendo");
call add_concept_translation (478,"No se realizaron cambios en el régimen de tratamiento de TB");
call add_concept_translation (523,"Problema con el suministro del medicamento o su administración");
call add_concept_translation (538,"g/L");
call add_concept_translation (625,"Administración bilateral oídos");
call add_concept_translation (630,"Administración vaginal");
call add_concept_translation (632,"Administración por sonda nasogástrica");
call add_concept_translation (635,"Estado del Indice de Masa Corporal");
call add_concept_translation (638,"Indice de Masa Corporal anormal");
call add_concept_translation (663,"6 meses post tratamiento");
call add_concept_translation (670,"Complejos ventriculares prematuros");
call add_concept_translation (677,"Cambio planificado");
call add_concept_translation (681,"Régimen que incluye drogas de segunda línea");
call add_concept_translation (685,"Otro régimen PDR");
call add_concept_translation (687,"Régimen XDR");
call add_concept_translation (690,"Régimen TB MDR acortado de 9 meses");
call add_concept_translation (716,"No detectado");
call add_concept_translation (725,"Esquema A");
call add_concept_translation (728,"Esquema D");
call add_concept_translation (734,"Perdido en el seguimiento");
call add_concept_translation (788,"Seguimiento 6 meses post tratamiento");
call add_concept_translation (815,"No realizado");
call add_concept_translation (855,"Moderado");
call add_concept_translation (856,"Moderadamente severo");
call add_concept_translation (919,"Causa que no sea TB");
call add_concept_translation (926,"Reversión bacteriológica");
call add_concept_translation (928,"Reacción adversa al medicamento");
call add_concept_translation (931,"Paciente rehusó el seguimiento");
call add_concept_translation (932,"Abuso de sustancias");
call add_concept_translation (933,"Problema social");
call add_concept_translation (935,"Sin confianza en el tratamiento");
call add_concept_translation (936,"No ingresado");
call add_concept_translation (955,"Paciente rehusó el seguimiento");
call add_concept_translation (981,"Personal ausente");
call add_concept_translation (984,"Problema financiero");
call add_concept_translation (985,"Relacionado al trabajo");
call add_concept_translation (1039,"Paciente");
call add_concept_translation (1040,"Compañero");
call add_concept_translation (1050,"Fármaco retirado");
call add_concept_translation (1064,"Masculino");
call add_concept_translation (1073,"Tórax, 1 vista (radiografía)");
call add_concept_translation (1075,"Radiología");
call add_concept_translation (1094,"Escaso");
call add_concept_translation (1108,"Medio");
call add_concept_translation (1111,"RIF resistencia detectada");
call add_concept_translation (1112,"RIF resistencia no detectada");
call add_concept_translation (1134,"Positivo para M. tuberculosis");
call add_concept_translation (1135,"Negativo para M. tuberculosis");
call add_concept_translation (1137,"Sólo positivo para otro mycobacterium");
call add_concept_translation (1170,"Mutación");
call add_concept_translation (1235,"Tenofovir (TDF)");
call add_concept_translation (1255,"7 días por semana");
call add_concept_translation (1258,"Claritromicina ");
call add_concept_translation (1303,"Glucosa (ayunas) anormal");
call add_concept_translation (1404,"Desórden neurosensorio");
call add_concept_translation (1430,"Dosis reducida permanentemente");
call add_concept_translation (1473,"Muerte");
call add_concept_translation (1474,"Pone en riesgo la vida");
call add_concept_translation (1476,"Discapacidad/incapacidad");
call add_concept_translation (1551,"Estado de admisión no definido");
call add_concept_translation (1553,"Paciente en lista de espera");
call add_concept_translation (1554,"Paciente excluido de la admisión");
call add_concept_translation (1585,"Problema social");
call add_concept_translation (1640,"Magnesio");
call add_concept_translation (1641,"Resultado de Calcio Ionizado");
call add_concept_translation (1642,"Nitrógeno Ureico en sangre");
call add_concept_translation (1650,"Resultados de Laboratorio - Bioquímica");
call add_concept_translation (1657,"Hemoglobina g/dl anormal");
call add_concept_translation (1668,"Glóbulos rojos (con otras unidades) anormal");
call add_concept_translation (1669,"Conteo de glóbulos rojos  (x10^12/L)");
call add_concept_translation (1672,"Glóbulos blancos anormal");
call add_concept_translation (1674,"Glóbulos blancos (otras unidades) anormal");
call add_concept_translation (1675,"Conteo de glóbulos blancos (cel/mm3)");
call add_concept_translation (1676,"Recuento absoluto de neutrófilos anormal");
call add_concept_translation (1680,"Recuento absoluto de neutrófilos anormal (otro resultado de la prueba)");
call add_concept_translation (1683,"Potasio sérico (anormal)");
call add_concept_translation (1685,"Potasio (otro) anormal");
call add_concept_translation (1690,"Magnesio (mg/dL)");
call add_concept_translation (1691,"Calcio  ionizado resultado de la prueba anormal");
call add_concept_translation (1692,"Calcio ionizado (mEq/L)");
call add_concept_translation (1695,"Nitrógeno Ureico en sangre anormal");
call add_concept_translation (1697,"Urea anormal (otro)");
call add_concept_translation (1698,"Urea (mmol/L)");
call add_concept_translation (1703,"Glucosa sérica anormal");
call add_concept_translation (1705,"Glucosa (otro) anormal");
call add_concept_translation (1708,"Glucosa (ayunas) (mg/dL)");
call add_concept_translation (1709,"Glucosa (ayunas) otro, anormal");
call add_concept_translation (1717,"Transaminasa glutamico oxalacética sérica anormal");
call add_concept_translation (1719,"Transaminasa glutamico piruvica sérica anormal");
call add_concept_translation (1721,"Bilirrubina total anormal");
call add_concept_translation (1725,"Albúmina sérica anormal");
call add_concept_translation (1727,"Albúmina sérica");
call add_concept_translation (1729,"Albúmina sérica (g/L)");
call add_concept_translation (1730,"Todos los Medicamentos de TB");
call add_concept_translation (1737,"No se sabe");
call add_concept_translation (1752,"No se sabe");
call add_concept_translation (1754,"Enero");
call add_concept_translation (1755,"Febrero");
call add_concept_translation (1758,"Mayo");
call add_concept_translation (1766,"Fecha de carga viral");
call add_concept_translation (1767,"2010");
call add_concept_translation (1768,"2011");
call add_concept_translation (1770,"2013");
call add_concept_translation (1773,"2016");
call add_concept_translation (1777,"2020");
call add_concept_translation (1779,"Otros relacionados al programa");
call add_concept_translation (1792,"Razón para la próxima visita");
call add_concept_translation (1793,"Otra evaluación, motivo");
call add_concept_translation (1794,"Razón para la próxima visita");
call add_concept_translation (1795,"Otra evaluación, motivo");
call add_concept_translation (1797,"Carga viral HIV");
call add_concept_translation (1804,"2002");
call add_concept_translation (1806,"2004");
call add_concept_translation (1807,"2005");
call add_concept_translation (1809,"2007");
call add_concept_translation (1810,"2008");
call add_concept_translation (1812,"Cálculos mensuales}");
call add_concept_translation (1815,"Izquierda");
call add_concept_translation (1816,"Derecha");
call add_concept_translation (1820,"Ganglio linfático");
call add_concept_translation (1821,"Líquido ascítico");
call add_concept_translation (1822,"Biopsia de hueso");
call add_concept_translation (1823,"Biopsia de otro tejido");
call add_concept_translation (1827,"Resuelto con secuelas (EAS)");
call add_concept_translation (1831,"EA ID N°");
call add_concept_translation (1840,"N° de Historia Clínica");
call add_concept_translation (1846,"Azitromicina");
call add_concept_translation (1847,"Cefepime");
call add_concept_translation (1849,"EndTB");
call add_concept_translation (1856,"Detalles de electrocardiograma");
call add_concept_translation (1858,"Hematocrito");
call add_concept_translation (1859,"Conteo de plaquetas");
call add_concept_translation (1864,"Potasio");
call add_concept_translation (1867,"Urea");
call add_concept_translation (1868,"Creatinina");
call add_concept_translation (1870,"Glucosa (ayunas)");
call add_concept_translation (1873,"Lipasa");
call add_concept_translation (1880,"Audiometría");
call add_concept_translation (1883,"Presión sanguínea");
call add_concept_translation (1893,"Conteo anormal de CD4");
call add_concept_translation (1897,"Conteo anormal de CD4, otro");
call add_concept_translation (2228,"Lima, Lima, Blufstein");
call add_concept_translation (2229,"Lima, Comas, Hospital Nacional Sergio Bernales");
call add_concept_translation (2234,"Magnesio");
call add_concept_translation (2237,"0 to 20 db");
call add_concept_translation (2238,"21 to 40 dB");
call add_concept_translation (2239,"41 to 55 dB");
call add_concept_translation (2240,"56 to 70 dB");
call add_concept_translation (2241,"71 to 90 dB");
call add_concept_translation (2242,"91+ dB");
call add_concept_translation (2250,"Imp");
call add_concept_translation (2251,"Imp + Amx/Clv");
call add_concept_translation (2252,"Imp+ Amx/Clv+ Km");
call add_concept_translation (2253,"IMp+ Amx/Clv+Cm");
call add_concept_translation (2254,"No actualmente");
call add_concept_translation (2256,"Complicación");
call add_concept_translation (2257,"Solicitud del paciente");
call add_concept_translation (2259,"Tasa general de DOT (X)");
call add_concept_translation (2260,"Bedaquilina");
call add_concept_translation (2261,"Delamanid");
call add_concept_translation (2262,"Linezolid");
call add_concept_translation (2263,"Clofazimina");
call add_concept_translation (2270,"Instituto Nacional de Salud - INS");
call add_concept_translation (2271,"C.S. Ermitaño Alto");
call add_concept_translation (2272,"C.S.M.I Ancón");
call add_concept_translation (2275,"CS Comas (Lima, Comas)");
call add_concept_translation (2280,"Hospital La Caleta (Chimbote)");
call add_concept_translation (2281,"PS Villa Venturo (Lima, Chorrillos)");
call add_concept_translation (2282,"PS Cerro Candela (Lima, SMP)");
call add_concept_translation (2284,"Establecimiento Penal Lurigancho (Lima, SJL)");
call add_concept_translation (2294,"Inyección");
call add_concept_translation (2296,"PS Amauta (Lima, Ate)");
call add_concept_translation (2297,"PS La Rinconada (Lima, SJM)");
call add_concept_translation (2298,"Hospital de Huaycan (Lima, Ate)");
call add_concept_translation (2299,"Centro Médico El Nazareno (Lima, SJM)");
call add_concept_translation (2305,"CMI San José (Lima, VES)");
call add_concept_translation (2310,"Alprazolam 0.5 mg (tabletas)");
call add_concept_translation (2311,"Diclofenaco sódico gel");
call add_concept_translation (2312,"Sulpiride 200 mg (tabletas)");
call add_concept_translation (2313,"Aplicación");
call add_concept_translation (2314,"Sublingual");
call add_concept_translation (2315,"Oftálmica");
call add_concept_translation (2316,"CS El Porvenir (Lima, La Victoria)");
call add_concept_translation (2325,"Laboratorio de Socios en Salud Sucursal Peru (Lima, Carabayllo)");
call add_concept_translation (2326,"Duración del tratamiento");
call add_concept_translation (2334,"2 días por semana");
call add_concept_translation (2336,"solución oral");
call add_concept_translation (2337,"Tableta dispersable");
call add_concept_translation (2338,"Tableta blíster");
call add_concept_translation (2339,"Ungüento");
call add_concept_translation (2340,"Crema");
call add_concept_translation (2341,"Solución para nebulización");
call add_concept_translation (2342,"Inhalador");
call add_concept_translation (2343,"Polvo para suspensión oral");
call add_concept_translation (2344,"Polvo para inyección");
call add_concept_translation (2345,"Suspensión oral");
call add_concept_translation (2346,"Paquete");
call add_concept_translation (2347,"Tableta blanda");
call add_concept_translation (2348,"Gotas oftálmicas");
call add_concept_translation (2349,"Solución para aplicación tópica");
call add_concept_translation (2350,"Botella");
call add_concept_translation (2351,"Gotas óticas");
call add_concept_translation (2352,"Bolsa para infusión endovenosa");
call add_concept_translation (2353,"Para inyección");
call add_concept_translation (2354,"Jarabe oral");
call add_concept_translation (2355,"Tableta blíster");
call add_concept_translation (2356,"Jarabe");
call add_concept_translation (2357,"Polvo + solvente 1ml");
call add_concept_translation (2358,"Polvo + solvente 0.5ml");
call add_concept_translation (2359,"Solución oral, 240ml");
call add_concept_translation (2360,"Gel");
call add_concept_translation (2361,"Para inyección (espinal)");
call add_concept_translation (2362,"Píldoras");
call add_concept_translation (2363,"Supositorio vaginal");
call add_concept_translation (2364,"Comprimido de liberación lenta");
call add_concept_translation (2365,"Tableta dispersable");
call add_concept_translation (2366,"Tableta oral");
call add_concept_translation (2367,"Loción");
call add_concept_translation (2368,"Tableta base");
call add_concept_translation (2369,"Solución");
call add_concept_translation (2370,"Polvo + solvente");
call add_concept_translation (2371,"Inhalador oral");
call add_concept_translation (2372,"Solución para nebulización");
call add_concept_translation (2373,"Gel");
call add_concept_translation (2374,"Ungüento oftálmico");
call add_concept_translation (2375,"Ungüento para la piel");
call add_concept_translation (2759,"CS Madre Teresa Calcuta (Lima, El Agustino)");
call add_concept_translation (2760,"Dianóstico curado");
call add_concept_translation (2761,"No");
call add_concept_translation (2762,"Si");
call add_concept_translation (2763,"Pendiente");
call add_concept_translation (2764,"No es posible");
call add_concept_translation (2765,"Fecha");
call add_concept_translation (2766,"Imagen");
call add_concept_translation (2767,"Descripción");
call add_concept_translation (2768,"Documentos");
call add_concept_translation (2769,"Hepatitis C PCR");
call add_concept_translation (2770,"Hepatitis C carga viral");
call add_concept_translation (2771,"Hepatitis C genotype");
call add_concept_translation (2777,"CS Mangomarca (Lima, SJL)");
call add_concept_translation (2778,"CS Surco (Lima, Surco)");
call add_concept_translation (2779,"PS José Carlos Mariátegui V Etapa (Lima, SJL)");
call add_concept_translation (2780,"PS Valle Bajo (Lima, VMT)");
call add_concept_translation (2781,"CS Nueva Esperanza (Lima, VMT)");
call add_concept_translation (2782,"Carga viral indetectable");
call add_concept_translation (2783,"Si los resultados de carga viral son indetectables, escriba los resultados aquí (por ejemplo, '<20')");
call add_concept_translation (2786,"Este resultado proviene de un reporte de laboratorio o de un formato de endTB que fue transcrito de un reporte de laboratorio?");
call add_concept_translation (2787,"Si es no, de dónde proviene?");
call add_concept_translation (2791,"Es el día de la fecha de inicio de tratamiento anti TB previo estimado?");
call add_concept_translation (2792,"Es el mes de la fecha de inicio de tratamiento anti TB previo estimado?");
call add_concept_translation (2793,"Es el año de la fecha de inicio de tratamiento anti TB previo estimado?");
call add_concept_translation (2794,"Es el día de la fecha de fin de tratamiento anti TB previo estimado?");
call add_concept_translation (2795,"Es el mes de la fecha de fin de tratamiento anti TB previo estimado?");
call add_concept_translation (2796,"Es el año de la fecha de fin de tratamiento anti TB previo estimado?");
call add_concept_translation (2797,"Es el día de la fecha de CD4 estimado?");
call add_concept_translation (2798,"Es el mes de la fecha de CD4 estimado?");
call add_concept_translation (2799,"Es el año de la fecha de CD4 estimado?");
call add_concept_translation (2800,"Es el día de la fecha de carga viral estimado?");
call add_concept_translation (2801,"Es el mes de la fecha de carga viral estimado?");
call add_concept_translation (2802,"Es el año de la fecha de carga viral estimado?");
call add_concept_translation (2803,"Es el día de la fecha de inicio de ARV estimado?");
call add_concept_translation (2804,"Es el mes de la fecha de inicio de ARV estimado?");
call add_concept_translation (2805,"Es el año de la fecha de inicio de ARV estimado?");
call add_concept_translation (2806,"Es el día de la fecha de diagnóstico de TB MDR estimado?");
call add_concept_translation (2807,"Es el mes de la fecha de diagnóstico de TB MDR estimado?");
call add_concept_translation (2808,"Es el año de la fecha de diagnóstico de TB MDR estimado?");
call add_concept_translation (2809,"Es el día de la fecha de inicio de tratamiento estimado?");
call add_concept_translation (2810,"Es el mes de la fecha de inicio de tratamiento estimado?");
call add_concept_translation (2811,"Es el año de la fecha de inicio de tratamiento estimado?");
call add_concept_translation (2812,"Es el día de la fecha de muerte antes del inicio de tratamiento estimado?");
call add_concept_translation (2813,"Es el mes de la fecha de muerte antes del inicio de tratamiento estimado?");
call add_concept_translation (2814,"Es el año de la fecha de muerte antes del inicio de tratamiento estimado?");
call add_concept_translation (2815,"Es el día de la fecha de inicio del EA estimado?");
call add_concept_translation (2816,"Es el mes de la fecha de inicio del EA estimado?");
call add_concept_translation (2817,"Es el año de la fecha de inicio del EA estimado?");
call add_concept_translation (2818,"Es el día de la fecha de reporte del EA estimado?");
call add_concept_translation (2819,"Es el mes de la fecha de reporte del EA estimado?");
call add_concept_translation (2820,"Es el año de la fecha de reporte del EA estimado?");
call add_concept_translation (2821,"Es el día de la fecha de resultado del EA estimado?");
call add_concept_translation (2822,"Es el mes de la fecha de resultado del EA estimado?");
call add_concept_translation (2823,"Es el año de la fecha de resultado del EA estimado?");
call add_concept_translation (2824,"Es el día de la fecha de inicio del EAS estimado?");
call add_concept_translation (2825,"Es el mes de la fecha de inicio del EAS estimado?");
call add_concept_translation (2826,"Es el año de la fecha de inicio del EAS estimado?");
call add_concept_translation (2827,"Es el día de la fecha de reporte del EAS estimado?");
call add_concept_translation (2828,"Es el mes de la fecha de reporte del EAS estimado?");
call add_concept_translation (2829,"Es el año de la fecha de reporte del EAS estimado?");
call add_concept_translation (2830,"Es el día de la fecha en que el evento se volvió serio estimado?");
call add_concept_translation (2831,"Es el mes de la fecha en que el evento se volvió serio estimado?");
call add_concept_translation (2832,"Es el año de la fecha en que el evento se volvió serio estimado?");
call add_concept_translation (2833,"Es el día de la fecha de resultado del EAS estimado?");
call add_concept_translation (2834,"Es el mes de la fecha de resultado del EAS estimado?");
call add_concept_translation (2835,"Es el año de la fecha de resultado del EAS estimado?");
call add_concept_translation (2836,"Es el día de la fecha de hospitalización estimado?");
call add_concept_translation (2837,"Es el mes de la fecha de hospitalización estimado?");
call add_concept_translation (2838,"Es el año de la fecha de hospitalización estimado?");
call add_concept_translation (2839,"Es el día de la fecha de alta hospitaliaria estimado?");
call add_concept_translation (2840,"Es el mes de la fecha de alta hospitaliaria estimado?");
call add_concept_translation (2841,"Es el año de la fecha de alta hospitaliaria estimado?");
call add_concept_translation (2842,"Es el día de la fecha de colección de muestra estimado?");
call add_concept_translation (2843,"Es el mes de la fecha de colección de muestra estimado?");
call add_concept_translation (2844,"Es el año de la fecha de colección de muestra estimado?");
call add_concept_translation (2845,"Es el día de la fecha de reporte estimado?");
call add_concept_translation (2846,"Es el mes de la fecha de reporte estimado?");
call add_concept_translation (2847,"Es el año de la fecha de reporte estimado?");
call add_concept_translation (2848,"Es el día de la fecha de parto estimado?");
call add_concept_translation (2849,"Es el mes de la fecha de parto estimado?");
call add_concept_translation (2850,"Es el año de la fecha de parto estimado?");
call add_concept_translation (2851,"Es el día de la fecha de fin de tratamiento estimado?");
call add_concept_translation (2852,"Es el mes de la fecha de fin de tratamiento estimado?");
call add_concept_translation (2853,"Es el año de la fecha de fin de tratamiento estimado?");
call add_concept_translation (2854,"Es el día de la fecha en que se decidió el fin del tratamiento estimado?");
call add_concept_translation (2855,"Es el mes de la fecha en que se decidió el fin del tratamiento estimado?");
call add_concept_translation (2856,"Es el año de la fecha en que se decidió el fin del tratamiento estimado?");
call add_concept_translation (2857,"Es el día de la fecha de muerte estimado?");
call add_concept_translation (2858,"Es el mes de la fecha de muerte estimado?");
call add_concept_translation (2859,"Es el año de la fecha de muerte estimado?");
call add_concept_translation (2860,"Es el día de la fecha de evaluación de resultado post tratamiento al 6to mes estimado?");
call add_concept_translation (2861,"Es el mes de la fecha de evaluación de resultado post tratamiento al 6to mes estimado?");
call add_concept_translation (2862,"Es el año de la fecha de evaluación de resultado post tratamiento al 6to mes estimado?");
call add_concept_translation (2863,"Es el día de la fecha de colección de muestra estimado?");
call add_concept_translation (2864,"Es el mes de la fecha de colección de muestra estimado?");
call add_concept_translation (2865,"Es el año de la fecha de colección de muestra estimado?");
call add_concept_translation (2869,"Es el día de la fecha de realización de la prueba Xpert estimado?");
call add_concept_translation (2870,"Es el mes de la fecha de realización de la prueba Xpert estimado?");
call add_concept_translation (2871,"Es el año de la fecha de realización de la prueba Xpert estimado?");
call add_concept_translation (2872,"Es el día de la fecha de siembra del cultivo estimado?");
call add_concept_translation (2873,"Es el mes de la fecha de siembra del cultivo estimado?");
call add_concept_translation (2874,"Es el año de la fecha de siembra del cultivo estimado?");
call add_concept_translation (2875,"Es el día de la fecha de realización de la prueba hain MTBDRplus estimado?");
call add_concept_translation (2876,"Es el mes de la fecha de realización de la prueba hain MTBDRplus estimado?");
call add_concept_translation (2877,"Es el año de la fecha de realización de la prueba hain MTBDRplus estimado?");
call add_concept_translation (2878,"Es el día de la fecha de realización de la prueba hain MTBDRsl estimado?");
call add_concept_translation (2879,"Es el mes de la fecha de realización de la prueba hain MTBDRsl estimado?");
call add_concept_translation (2880,"Es el año de la fecha de realización de la prueba hain MTBDRsl estimado?");
call add_concept_translation (2881,"Es la fecha de inicio de tratamiento anti TB previo estimada?");
call add_concept_translation (2882,"Es la fecha de fin de tratamiento anti TB previo estimada?");
call add_concept_translation (2883,"Es la fecha de CD4 estimada?");
call add_concept_translation (2884,"Es la fecha de carga viral estimada?");
call add_concept_translation (2885,"Es la fecha de inicio de ARV estimada?");
call add_concept_translation (2886,"Es la fecha de diagnóstico de TB MDR estimada?");
call add_concept_translation (2887,"Es la fecha de inicio de tratamiento estimada?");
call add_concept_translation (2888,"Es la fecha de muerte antes de inicio de tratamiento estimada?");
call add_concept_translation (2889,"Es la fecha de inicio de EA estimada?");
call add_concept_translation (2890,"Es la fecha de reporte de EA estimada?");
call add_concept_translation (2891,"Es la fecha de resultado de EA estimada?");
call add_concept_translation (2892,"Es la fecha de inicio de EAS estimada?");
call add_concept_translation (2893,"Es la fecha de reporte de EAS estimada?");
call add_concept_translation (2894,"Es la fecha en que el evento se volvió serio estimada?");
call add_concept_translation (2895,"Es la fecha de resultado de EAS estimada?");
call add_concept_translation (2896,"Es la fecha de hospitalización estimada?");
call add_concept_translation (2897,"Es la fecha de hospitalización estimada?");
call add_concept_translation (2898,"Es la fecha de alta hospitalaria estimada?");
call add_concept_translation (2899,"Es la fecha de colección de muestra estimada?");
call add_concept_translation (2900,"Es la fecha de colección de muestra estimada?");
call add_concept_translation (2902,"Es la fecha de realización de la prueba Xpert estimada?");
call add_concept_translation (2903,"Es la fecha de siembra del cultivo estimada?");
call add_concept_translation (2904,"Es la fecha de realización de la prueba hain MTBDRplus estimada?");
call add_concept_translation (2905,"Es la fecha de realización de la prueba hain MTBDRsl estimada?");
call add_concept_translation (2906,"Es la fecha de reporte estimada?");
call add_concept_translation (2907,"Es la fecha de parto estimada?");
call add_concept_translation (2908,"Es la fecha de fin de tratamiento estimada?");
call add_concept_translation (2909,"Es la fecha en que se decidió el fin del tratamiento estimada?");
call add_concept_translation (2910,"Es la fecha de muerte estimada?");
call add_concept_translation (2911,"Es la fecha de evaluación de resultado post tratamiento al 6to mes estimado?");
